export const TYPE = {
  THIN: 'Montserrat-Thin',
  THIN_ITALIC: 'Montserrat-ThinItalic',
  SEMIBOLD_ITALIC: 'Montserrat-SemiBoldItalic',
  SEMIBOLD: 'Montserrat-SemiBold',
  REGULAR: 'Montserrat-Regular',
  MEDIUM_ITALIC: 'Montserrat-MediumItalic',
  MEDIUM: 'Montserrat-Medium',
  LIGHT_ITALIC: 'Montserrat-LightItalic',
  LIGHT: 'Montserrat-Light',
  ITALIC: 'Montserrat-Italic',
  EXTRA_LIGHT_ITALIC: 'Montserrat-ExtraLightItalic',
  EXTRA_LIGHT: 'Montserrat-ExtraLight',
  EXTRABOLD_ITALIC: 'Montserrat-ExtraBoldItalic',
  EXTRABOLD: 'Montserrat-ExtraBold',
};
