export const resources = {
  vi: {
    home: {
      hello: 'Xin chào',
      goodMoring: 'Buổi sáng vui vẻ',
      goodAfternoon: 'Buổi chiều vui vẻ',
      goodEvening: 'Buổi tối vui vẻ',
      goodNight: 'Chúc ngủ ngon',
      dailyGoal: 'Mục tiêu hằng ngày',
      water: 'Nước lọc',
      beer: 'Bia',
      coffee: 'Cà phê',
      milkTea: 'Trà sữa',
      juice: 'Nước trái cây',
      soda: 'Nước ngọt',
      milk: 'Sữa',
      tea: 'Trà',
      wine: 'Rượu vang',
      coconut: 'Nước dừa',
      add: 'Thêm mới',
      noData: 'Không có dữ liệu',
    },
    common: {
      ok: 'Đồng ý',
    },
    statistics: {
      sun: 'Th 2',
      mon: 'Th 3',
      tue: 'Th 4',
      web: 'Th 5',
      thu: 'Th 6',
      fri: 'Th 7',
      sat: 'CN',
      week: 'Tuần',
      month: 'Tháng',
      year: 'Năm',
    },
    settings: {
      settings: 'Cài đặt',
      livingTime: 'Thời gian sinh hoạt',
      gender: 'Giới tính',
      weight: 'Cân nặng',
      dailyGoals: 'Mục tiêu hằng ngày',
      glassOfWater: 'Ly nước',
      language: 'Ngôn ngữ',
      reminderDistance: 'Khoảng cách nhắc nhở',
    },
  },

  en: {
    home: {
      hello: 'Hello',
      goodMoring: 'Good Morning',
      goodAfternoon: 'Good Afternoon',
      goodEvening: 'Good Evening',
      goodNight: 'Good Night',
      dailyGoal: 'Daily goal',
      water: 'Water',
      beer: 'Beer',
      coffee: 'Coffee',
      milkTea: 'Milk Tea',
      juice: 'Fruit Juice',
      soda: 'Soda',
      milk: 'Milk',
      tea: 'Tea',
      wine: 'Wine',
      coconut: 'Coconut',
      add: 'Add',
      noData: 'No data',
    },
    common: {
      ok: 'OK',
    },
    statistics: {
      sun: 'Sun',
      mon: 'Mon',
      tue: 'Tue',
      web: 'Web',
      thu: 'Thu',
      fri: 'Fri',
      sat: 'Sat',
      week: 'Week',
      month: 'Month',
      year: 'Year',
    },

    settings: {
      settings: 'Settings',
      livingTime: 'Living time',
      gender: 'Gender',
      weight: 'Weight',
      dailyGoals: 'Daily goals',
      glassOfWater: 'Glass of water',
      language: 'Language',
      reminderDistance: 'Reminder distance',
    },
  },
};
